export const SET_IS_AUTH = "SET_IS_AUTH";
export const SET_ADD_PRODUCT_MODAL_SHOW = "SET_ADD_PRODUCT_MODAL_SHOW";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const SET_CATEGORY_MODAL_SHOW = "SET_CATEGORY_MODAL_SHOW";
export const SET_ALERT = "SET_ALERT";
